spring.application.name: mall-admin
spring.session.redis.namespace: session:${spring.application.name}
spring:
  datasource:
    table:
      prefix: merchant_
schedule.cron.sub-auth-sync-job: "0 0/5 * * * ?"